name: .NET

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore -r win-x64
    - name: Build
      run: |
        cd Scarab
        dotnet publish --no-restore -r win-x64 -p:PublishSingleFile=true -p:Configuration=Release --self-contained true
        cd ..
    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: Scarab-Windows
        path: Scarab/bin/Release/net6.0/win-x64/publish/
